# Generated by Django 2.0.7 on 2021-11-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Email', models.TextField(blank=True, default='', max_length=300)),
                ('Username', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
