# Generated by Django 3.2.9 on 2021-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr. ', 'Mr. '), ('Mrs. ', 'Mrs. '), ('Ms. ', 'Ms. ')], default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
