# Generated by Django 3.2.9 on 2021-11-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20211105_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(choices=[('Mr. ', 'Mr. '), ('Ms. ', 'Ms. '), ('Mrs. ', 'Mrs. ')], default='', max_length=60)),
                ('First_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=60)),
                ('Email', models.TextField(blank=True, default='', max_length=300)),
                ('Username', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
